debug: false

web:
  upload-path: F:/log/

server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /templates
spring:
  devtools:
    restart:
      enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  application:
    name: templates
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.18:3306/templates?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    minIdle: 5
    maxActive: 20
    maxWait: 600000
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # 上传文件总的最大值
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 2MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置枚举 支持通配符 * 或者 ; 分割
mybatis-plus:
  type-enums-package: com.cyb.*
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

logging:
  level:
    com:
      cyb:
        blogserver:
          dao: debug